name: ci
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run Hello World
        run: echo hello world

      # - name: Setup ArgoCD CLI 
      #   uses: imajeetyadav/argocd-cli@v1
      #   with:
      #     version: v2.5.7 # optional 
      - name: argocli cmd
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
          echo ${{ github.server_url }}/${{ github.repository }}
          argocd login argocd.saasdevtoppers.click --username admin --password admin@123
          argocd repo add https://github.com/kalpeshkolap/git-actions.git --password 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 --grpc-web

